import { IsoCode } from '@shared/enums';

export type CountryCodeConfig = {
  code: IsoCode;
  dialingCode: string;
  id: string;
  localizedName: string;
  englishName: string;
  nativeName: string;
};

export const countryCodeList: CountryCodeConfig[] = [
  {
    code: IsoCode.AD,
    dialingCode: '376',
    id: '1',
    localizedName: '安道爾',
    englishName: 'Andorra',
    nativeName: 'Andorra',
  },
  {
    code: IsoCode.AE,
    dialingCode: '971',
    id: '2',
    localizedName: '阿聯',
    englishName: 'United Arab Emirates',
    nativeName: 'دولة الإمارات العربية المتحدة',
  },
  {
    code: IsoCode.AF,
    dialingCode: '93',
    id: '3',
    localizedName: '阿富汗',
    englishName: 'Afghanistan',
    nativeName: 'افغانستان',
  },
  {
    code: IsoCode.AG,
    dialingCode: '1268',
    id: '4',
    localizedName: '安地卡及巴布達',
    englishName: 'Antigua and Barbuda',
    nativeName: 'Antigua and Barbuda',
  },
  {
    code: IsoCode.AI,
    dialingCode: '1264',
    id: '5',
    localizedName: '安圭拉',
    englishName: 'Anguilla',
    nativeName: 'Anguilla',
  },
  {
    code: IsoCode.AL,
    dialingCode: '355',
    id: '6',
    localizedName: '阿爾巴尼亞',
    englishName: 'Albania',
    nativeName: 'Shqipëria',
  },
  {
    code: IsoCode.AM,
    dialingCode: '374',
    id: '7',
    localizedName: '亞美尼亞',
    englishName: 'Armenia',
    nativeName: 'Հայաստան',
  },
  {
    code: IsoCode.AO,
    dialingCode: '244',
    id: '8',
    localizedName: '安哥拉',
    englishName: 'Angola',
    nativeName: 'Angola',
  },
  {
    code: IsoCode.AQ,
    dialingCode: '672',
    id: '9',
    localizedName: '南極洲',
    englishName: 'Antarctica',
    nativeName: 'Antarctica',
  },
  {
    code: IsoCode.AR,
    dialingCode: '54',
    id: '10',
    localizedName: '阿根廷',
    englishName: 'Argentina',
    nativeName: 'Argentina',
  },
  {
    code: IsoCode.AS,
    dialingCode: '1684',
    id: '11',
    localizedName: '美屬薩摩亞',
    englishName: 'American Samoa',
    nativeName: 'American Samoa',
  },
  {
    code: IsoCode.AT,
    dialingCode: '43',
    id: '12',
    localizedName: '奧地利',
    englishName: 'Austria',
    nativeName: 'Österreich',
  },
  {
    code: IsoCode.AU,
    dialingCode: '61',
    id: '13',
    localizedName: '澳洲',
    englishName: 'Australia',
    nativeName: 'Australia',
  },
  {
    code: IsoCode.AW,
    dialingCode: '297',
    id: '14',
    localizedName: '阿魯巴',
    englishName: 'Aruba',
    nativeName: 'Aruba',
  },
  {
    code: IsoCode.AX,
    dialingCode: '358',
    id: '15',
    localizedName: '奧蘭',
    englishName: 'Åland',
    nativeName: 'Åland',
  },
  {
    code: IsoCode.AZ,
    dialingCode: '994',
    id: '16',
    localizedName: '亞塞拜然',
    englishName: 'Azerbaijan',
    nativeName: 'Azərbaycan',
  },
  {
    code: IsoCode.BA,
    dialingCode: '387',
    id: '17',
    localizedName: '波士尼亞與赫塞哥維納',
    englishName: 'Bosnia and Herzegovina',
    nativeName: 'Bosna i Hercegovina',
  },
  {
    code: IsoCode.BB,
    dialingCode: '1246',
    id: '18',
    localizedName: '巴貝多',
    englishName: 'Barbados',
    nativeName: 'Barbados',
  },
  {
    code: IsoCode.BD,
    dialingCode: '880',
    id: '19',
    localizedName: '孟加拉',
    englishName: 'Bangladesh',
    nativeName: 'Bangladesh',
  },
  {
    code: IsoCode.BE,
    dialingCode: '32',
    id: '20',
    localizedName: '比利時',
    englishName: 'Belgium',
    nativeName: 'België',
  },
  {
    code: IsoCode.BF,
    dialingCode: '226',
    id: '21',
    localizedName: '布吉納法索',
    englishName: 'Burkina Faso',
    nativeName: 'Burkina Faso',
  },
  {
    code: IsoCode.BG,
    dialingCode: '359',
    id: '22',
    localizedName: '保加利亞',
    englishName: 'Bulgaria',
    nativeName: 'България',
  },
  {
    code: IsoCode.BH,
    dialingCode: '973',
    id: '23',
    localizedName: '巴林',
    englishName: 'Bahrain',
    nativeName: '‏البحرين',
  },
  {
    code: IsoCode.BI,
    dialingCode: '257',
    id: '24',
    localizedName: '蒲隆地',
    englishName: 'Burundi',
    nativeName: 'Burundi',
  },
  {
    code: IsoCode.BJ,
    dialingCode: '229',
    id: '25',
    localizedName: '貝南',
    englishName: 'Benin',
    nativeName: 'Bénin',
  },
  {
    code: IsoCode.BL,
    dialingCode: '590',
    id: '26',
    localizedName: '聖巴瑟米',
    englishName: 'Saint Barthélemy',
    nativeName: 'Saint-Barthélemy',
  },
  {
    code: IsoCode.BM,
    dialingCode: '1441',
    id: '27',
    localizedName: '百慕達',
    englishName: 'Bermuda',
    nativeName: 'Bermuda',
  },
  {
    code: IsoCode.BN,
    dialingCode: '673',
    id: '28',
    localizedName: '汶萊',
    englishName: 'Brunei',
    nativeName: 'Negara Brunei Darussalam',
  },
  {
    code: IsoCode.BO,
    dialingCode: '591',
    id: '29',
    localizedName: '玻利維亞',
    englishName: 'Bolivia',
    nativeName: 'Bolivia',
  },
  {
    code: IsoCode.BQ,
    dialingCode: '5997',
    id: '30',
    localizedName: '荷蘭加勒比區',
    englishName: 'Bonaire',
    nativeName: 'Bonaire',
  },
  {
    code: IsoCode.BR,
    dialingCode: '55',
    id: '31',
    localizedName: '巴西',
    englishName: 'Brazil',
    nativeName: 'Brasil',
  },
  {
    code: IsoCode.BS,
    dialingCode: '1242',
    id: '32',
    localizedName: '巴哈馬',
    englishName: 'Bahamas',
    nativeName: 'Bahamas',
  },
  {
    code: IsoCode.BT,
    dialingCode: '975',
    id: '33',
    localizedName: '不丹',
    englishName: 'Bhutan',
    nativeName: 'ʼbrug-yul',
  },
  {
    code: IsoCode.BV,
    dialingCode: '47',
    id: '34',
    localizedName: '布韋島',
    englishName: 'Bouvet Island',
    nativeName: 'Bouvetøya',
  },
  {
    code: IsoCode.BW,
    dialingCode: '267',
    id: '35',
    localizedName: '波札那',
    englishName: 'Botswana',
    nativeName: 'Botswana',
  },
  {
    code: IsoCode.BY,
    dialingCode: '375',
    id: '36',
    localizedName: '白俄羅斯',
    englishName: 'Belarus',
    nativeName: 'Белару́сь',
  },
  {
    code: IsoCode.BZ,
    dialingCode: '501',
    id: '37',
    localizedName: '貝里斯',
    englishName: 'Belize',
    nativeName: 'Belize',
  },
  {
    code: IsoCode.CA,
    dialingCode: '1',
    id: '38',
    localizedName: '加拿大',
    englishName: 'Canada',
    nativeName: 'Canada',
  },
  {
    code: IsoCode.CC,
    dialingCode: '61',
    id: '39',
    localizedName: '科科斯（基林）群島',
    englishName: 'Cocos [Keeling] Islands',
    nativeName: 'Cocos (Keeling) Islands',
  },
  {
    code: IsoCode.CD,
    dialingCode: '243',
    id: '40',
    localizedName: '剛果民主共和國',
    englishName: 'Democratic Republic of the Congo',
    nativeName: 'République démocratique du Congo',
  },
  {
    code: IsoCode.CF,
    dialingCode: '236',
    id: '41',
    localizedName: '中非',
    englishName: 'Central African Republic',
    nativeName: 'Ködörösêse tî Bêafrîka',
  },
  {
    code: IsoCode.CG,
    dialingCode: '242',
    id: '42',
    localizedName: '剛果共和國',
    englishName: 'Republic of the Congo',
    nativeName: 'République du Congo',
  },
  {
    code: IsoCode.CH,
    dialingCode: '41',
    id: '43',
    localizedName: '瑞士',
    englishName: 'Switzerland',
    nativeName: 'Schweiz',
  },
  {
    code: IsoCode.CI,
    dialingCode: '225',
    id: '44',
    localizedName: '象牙海岸',
    englishName: 'Ivory Coast',
    // eslint-disable-next-line quotes
    nativeName: "Côte d'Ivoire",
  },
  {
    code: IsoCode.CK,
    dialingCode: '682',
    id: '45',
    localizedName: '庫克群島',
    englishName: 'Cook Islands',
    nativeName: 'Cook Islands',
  },
  {
    code: IsoCode.CL,
    dialingCode: '56',
    id: '46',
    localizedName: '智利',
    englishName: 'Chile',
    nativeName: 'Chile',
  },
  {
    code: IsoCode.CM,
    dialingCode: '237',
    id: '47',
    localizedName: '喀麥隆',
    englishName: 'Cameroon',
    nativeName: 'Cameroon',
  },
  {
    code: IsoCode.CN,
    dialingCode: '86',
    id: '48',
    localizedName: '中國',
    englishName: 'China',
    nativeName: '中国',
  },
  {
    code: IsoCode.CO,
    dialingCode: '57',
    id: '49',
    localizedName: '哥倫比亞',
    englishName: 'Colombia',
    nativeName: 'Colombia',
  },
  {
    code: IsoCode.CR,
    dialingCode: '506',
    id: '50',
    localizedName: '哥斯大黎加',
    englishName: 'Costa Rica',
    nativeName: 'Costa Rica',
  },
  {
    code: IsoCode.CU,
    dialingCode: '53',
    id: '51',
    localizedName: '古巴',
    englishName: 'Cuba',
    nativeName: 'Cuba',
  },
  {
    code: IsoCode.CV,
    dialingCode: '238',
    id: '52',
    localizedName: '維德角',
    englishName: 'Cape Verde',
    nativeName: 'Cabo Verde',
  },
  {
    code: IsoCode.CW,
    dialingCode: '5999',
    id: '53',
    localizedName: '古拉索',
    englishName: 'Curacao',
    nativeName: 'Curaçao',
  },
  {
    code: IsoCode.CX,
    dialingCode: '61',
    id: '54',
    localizedName: '聖誕島',
    englishName: 'Christmas Island',
    nativeName: 'Christmas Island',
  },
  {
    code: IsoCode.CY,
    dialingCode: '357',
    id: '55',
    localizedName: '賽普勒斯',
    englishName: 'Cyprus',
    nativeName: 'Κύπρος',
  },
  {
    code: IsoCode.CZ,
    dialingCode: '420',
    id: '56',
    localizedName: '捷克',
    englishName: 'Czech Republic',
    nativeName: 'Česká republika',
  },
  {
    code: IsoCode.DE,
    dialingCode: '49',
    id: '57',
    localizedName: '德國',
    englishName: 'Germany',
    nativeName: 'Deutschland',
  },
  {
    code: IsoCode.DJ,
    dialingCode: '253',
    id: '58',
    localizedName: '吉布地',
    englishName: 'Djibouti',
    nativeName: 'Djibouti',
  },
  {
    code: IsoCode.DK,
    dialingCode: '45',
    id: '59',
    localizedName: '丹麥',
    englishName: 'Denmark',
    nativeName: 'Danmark',
  },
  {
    code: IsoCode.DM,
    dialingCode: '1767',
    id: '60',
    localizedName: '多米尼克',
    englishName: 'Dominica',
    nativeName: 'Dominica',
  },
  {
    code: IsoCode.DO,
    dialingCode: '1809,1829,1849',
    id: '61',
    localizedName: '多明尼加',
    englishName: 'Dominican Republic',
    nativeName: 'República Dominicana',
  },
  {
    code: IsoCode.DZ,
    dialingCode: '213',
    id: '62',
    localizedName: '阿爾及利亞',
    englishName: 'Algeria',
    nativeName: 'الجزائر',
  },
  {
    code: IsoCode.EC,
    dialingCode: '593',
    id: '63',
    localizedName: '厄瓜多',
    englishName: 'Ecuador',
    nativeName: 'Ecuador',
  },
  {
    code: IsoCode.EE,
    dialingCode: '372',
    id: '64',
    localizedName: '愛沙尼亞',
    englishName: 'Estonia',
    nativeName: 'Eesti',
  },
  {
    code: IsoCode.EG,
    dialingCode: '20',
    id: '65',
    localizedName: '埃及',
    englishName: 'Egypt',
    nativeName: 'مصر‎',
  },
  {
    code: IsoCode.EH,
    dialingCode: '212',
    id: '66',
    localizedName: '西撒哈拉',
    englishName: 'Western Sahara',
    nativeName: 'الصحراء الغربية',
  },
  {
    code: IsoCode.ER,
    dialingCode: '291',
    id: '67',
    localizedName: '厄利垂亞',
    englishName: 'Eritrea',
    nativeName: 'ኤርትራ',
  },
  {
    code: IsoCode.ES,
    dialingCode: '34',
    id: '68',
    localizedName: '西班牙',
    englishName: 'Spain',
    nativeName: 'España',
  },
  {
    code: IsoCode.ET,
    dialingCode: '251',
    id: '69',
    localizedName: '衣索比亞',
    englishName: 'Ethiopia',
    nativeName: 'ኢትዮጵያ',
  },
  {
    code: IsoCode.FI,
    dialingCode: '358',
    id: '70',
    localizedName: '芬蘭',
    englishName: 'Finland',
    nativeName: 'Suomi',
  },
  {
    code: IsoCode.FJ,
    dialingCode: '679',
    id: '71',
    localizedName: '斐濟',
    englishName: 'Fiji',
    nativeName: 'Fiji',
  },
  {
    code: IsoCode.FK,
    dialingCode: '500',
    id: '72',
    localizedName: '福克蘭群島',
    englishName: 'Falkland Islands',
    nativeName: 'Falkland Islands',
  },
  {
    code: IsoCode.FM,
    dialingCode: '691',
    id: '73',
    localizedName: '密克羅尼西亞聯邦',
    englishName: 'Micronesia',
    nativeName: 'Micronesia',
  },
  {
    code: IsoCode.FO,
    dialingCode: '298',
    id: '74',
    localizedName: '法羅群島',
    englishName: 'Faroe Islands',
    nativeName: 'Føroyar',
  },
  {
    code: IsoCode.FR,
    dialingCode: '33',
    id: '75',
    localizedName: '法國',
    englishName: 'France',
    nativeName: 'France',
  },
  {
    code: IsoCode.GA,
    dialingCode: '241',
    id: '76',
    localizedName: '加彭',
    englishName: 'Gabon',
    nativeName: 'Gabon',
  },
  {
    code: IsoCode.GB,
    dialingCode: '44',
    id: '77',
    localizedName: '英國',
    englishName: 'United Kingdom',
    nativeName: 'United Kingdom',
  },
  {
    code: IsoCode.GD,
    dialingCode: '1473',
    id: '78',
    localizedName: '格瑞那達',
    englishName: 'Grenada',
    nativeName: 'Grenada',
  },
  {
    code: IsoCode.GE,
    dialingCode: '995',
    id: '79',
    localizedName: '喬治亞',
    englishName: 'Georgia',
    nativeName: 'საქართველო',
  },
  {
    code: IsoCode.GF,
    dialingCode: '594',
    id: '80',
    localizedName: '法屬圭亞那',
    englishName: 'French Guiana',
    nativeName: 'Guyane française',
  },
  {
    code: IsoCode.GG,
    dialingCode: '44',
    id: '81',
    localizedName: '根西',
    englishName: 'Guernsey',
    nativeName: 'Guernsey',
  },
  {
    code: IsoCode.GH,
    dialingCode: '233',
    id: '82',
    localizedName: '迦納',
    englishName: 'Ghana',
    nativeName: 'Ghana',
  },
  {
    code: IsoCode.GI,
    dialingCode: '350',
    id: '83',
    localizedName: '直布羅陀',
    englishName: 'Gibraltar',
    nativeName: 'Gibraltar',
  },
  {
    code: IsoCode.GL,
    dialingCode: '299',
    id: '84',
    localizedName: '格陵蘭',
    englishName: 'Greenland',
    nativeName: 'Kalaallit Nunaat',
  },
  {
    code: IsoCode.GM,
    dialingCode: '220',
    id: '85',
    localizedName: '甘比亞',
    englishName: 'Gambia',
    nativeName: 'Gambia',
  },
  {
    code: IsoCode.GN,
    dialingCode: '224',
    id: '86',
    localizedName: '幾內亞',
    englishName: 'Guinea',
    nativeName: 'Guinée',
  },
  {
    code: IsoCode.GP,
    dialingCode: '590',
    id: '87',
    localizedName: '瓜地洛普',
    englishName: 'Guadeloupe',
    nativeName: 'Guadeloupe',
  },
  {
    code: IsoCode.GQ,
    dialingCode: '240',
    id: '88',
    localizedName: '赤道幾內亞',
    englishName: 'Equatorial Guinea',
    nativeName: 'Guinea Ecuatorial',
  },
  {
    code: IsoCode.GR,
    dialingCode: '30',
    id: '89',
    localizedName: '希臘',
    englishName: 'Greece',
    nativeName: 'Ελλάδα',
  },
  {
    code: IsoCode.GS,
    dialingCode: '500',
    id: '90',
    localizedName: '南喬治亞和南桑威奇群島',
    englishName: 'South Georgia and the South Sandwich Islands',
    nativeName: 'South Georgia',
  },
  {
    code: IsoCode.GT,
    dialingCode: '502',
    id: '91',
    localizedName: '瓜地馬拉',
    englishName: 'Guatemala',
    nativeName: 'Guatemala',
  },
  {
    code: IsoCode.GU,
    dialingCode: '1671',
    id: '92',
    localizedName: '關島',
    englishName: 'Guam',
    nativeName: 'Guam',
  },
  {
    code: IsoCode.GW,
    dialingCode: '245',
    id: '93',
    localizedName: '幾內亞比索',
    englishName: 'Guinea-Bissau',
    nativeName: 'Guiné-Bissau',
  },
  {
    code: IsoCode.GY,
    dialingCode: '592',
    id: '94',
    localizedName: '蓋亞那',
    englishName: 'Guyana',
    nativeName: 'Guyana',
  },
  {
    code: IsoCode.HK,
    dialingCode: '852',
    id: '95',
    localizedName: '香港',
    englishName: 'Hong Kong',
    nativeName: '香港',
  },
  {
    code: IsoCode.HM,
    dialingCode: '61',
    id: '96',
    localizedName: '赫德島和麥克唐納群島',
    englishName: 'Heard Island and McDonald Islands',
    nativeName: 'Heard Island and McDonald Islands',
  },
  {
    code: IsoCode.HN,
    dialingCode: '504',
    id: '97',
    localizedName: '宏都拉斯',
    englishName: 'Honduras',
    nativeName: 'Honduras',
  },
  {
    code: IsoCode.HR,
    dialingCode: '385',
    id: '98',
    localizedName: '克羅埃西亞',
    englishName: 'Croatia',
    nativeName: 'Hrvatska',
  },
  {
    code: IsoCode.HT,
    dialingCode: '509',
    id: '99',
    localizedName: '海地',
    englishName: 'Haiti',
    nativeName: 'Haïti',
  },
  {
    code: IsoCode.HU,
    dialingCode: '36',
    id: '100',
    localizedName: '匈牙利',
    englishName: 'Hungary',
    nativeName: 'Magyarország',
  },
  {
    code: IsoCode.ID,
    dialingCode: '62',
    id: '101',
    localizedName: '印度尼西亞',
    englishName: 'Indonesia',
    nativeName: 'Indonesia',
  },
  {
    code: IsoCode.IE,
    dialingCode: '353',
    id: '102',
    localizedName: '愛爾蘭',
    englishName: 'Ireland',
    nativeName: 'Éire',
  },
  {
    code: IsoCode.IL,
    dialingCode: '972',
    id: '103',
    localizedName: '以色列',
    englishName: 'Israel',
    nativeName: 'יִשְׂרָאֵל',
  },
  {
    code: IsoCode.IM,
    dialingCode: '44',
    id: '104',
    localizedName: '曼島',
    englishName: 'Isle of Man',
    nativeName: 'Isle of Man',
  },
  {
    code: IsoCode.IN,
    dialingCode: '91',
    id: '105',
    localizedName: '印度',
    englishName: 'India',
    nativeName: 'भारत',
  },
  {
    code: IsoCode.IO,
    dialingCode: '246',
    id: '106',
    localizedName: '英屬印度洋領地',
    englishName: 'British Indian Ocean Territory',
    nativeName: 'British Indian Ocean Territory',
  },
  {
    code: IsoCode.IQ,
    dialingCode: '964',
    id: '107',
    localizedName: '伊拉克',
    englishName: 'Iraq',
    nativeName: 'العراق',
  },
  {
    code: IsoCode.IR,
    dialingCode: '98',
    id: '108',
    localizedName: '伊朗',
    englishName: 'Iran',
    nativeName: 'ایران',
  },
  {
    code: IsoCode.IS,
    dialingCode: '354',
    id: '109',
    localizedName: '冰島',
    englishName: 'Iceland',
    nativeName: 'Ísland',
  },
  {
    code: IsoCode.IT,
    dialingCode: '39',
    id: '110',
    localizedName: '義大利',
    englishName: 'Italy',
    nativeName: 'Italia',
  },
  {
    code: IsoCode.JE,
    dialingCode: '44',
    id: '111',
    localizedName: '澤西',
    englishName: 'Jersey',
    nativeName: 'Jersey',
  },
  {
    code: IsoCode.JM,
    dialingCode: '1876',
    id: '112',
    localizedName: '牙買加',
    englishName: 'Jamaica',
    nativeName: 'Jamaica',
  },
  {
    code: IsoCode.JO,
    dialingCode: '962',
    id: '113',
    localizedName: '約旦',
    englishName: 'Jordan',
    nativeName: 'الأردن',
  },
  {
    code: IsoCode.JP,
    dialingCode: '81',
    id: '114',
    localizedName: '日本',
    englishName: 'Japan',
    nativeName: '日本',
  },
  {
    code: IsoCode.KE,
    dialingCode: '254',
    id: '115',
    localizedName: '肯亞',
    englishName: 'Kenya',
    nativeName: 'Kenya',
  },
  {
    code: IsoCode.KG,
    dialingCode: '996',
    id: '116',
    localizedName: '吉爾吉斯',
    englishName: 'Kyrgyzstan',
    nativeName: 'Кыргызстан',
  },
  {
    code: IsoCode.KH,
    dialingCode: '855',
    id: '117',
    localizedName: '柬埔寨',
    englishName: 'Cambodia',
    nativeName: 'Kâmpŭchéa',
  },
  {
    code: IsoCode.KI,
    dialingCode: '686',
    id: '118',
    localizedName: '吉里巴斯',
    englishName: 'Kiribati',
    nativeName: 'Kiribati',
  },
  {
    code: IsoCode.KM,
    dialingCode: '269',
    id: '119',
    localizedName: '葛摩',
    englishName: 'Comoros',
    nativeName: 'Komori',
  },
  {
    code: IsoCode.KN,
    dialingCode: '1869',
    id: '120',
    localizedName: '聖克里斯多福及尼維斯',
    englishName: 'Saint Kitts and Nevis',
    nativeName: 'Saint Kitts and Nevis',
  },
  {
    code: IsoCode.KP,
    dialingCode: '850',
    id: '121',
    localizedName: '北韓',
    englishName: 'North Korea',
    nativeName: '북한',
  },
  {
    code: IsoCode.KR,
    dialingCode: '82',
    id: '122',
    localizedName: '南韓',
    englishName: 'South Korea',
    nativeName: '대한민국',
  },
  {
    code: IsoCode.KW,
    dialingCode: '965',
    id: '123',
    localizedName: '科威特',
    englishName: 'Kuwait',
    nativeName: 'الكويت',
  },
  {
    code: IsoCode.KY,
    dialingCode: '1345',
    id: '124',
    localizedName: '開曼群島',
    englishName: 'Cayman Islands',
    nativeName: 'Cayman Islands',
  },
  {
    code: IsoCode.KZ,
    dialingCode: '76,77',
    id: '125',
    localizedName: '哈薩克',
    englishName: 'Kazakhstan',
    nativeName: 'Қазақстан',
  },
  {
    code: IsoCode.LA,
    dialingCode: '856',
    id: '126',
    localizedName: '寮國',
    englishName: 'Laos',
    nativeName: 'ສປປລາວ',
  },
  {
    code: IsoCode.LB,
    dialingCode: '961',
    id: '127',
    localizedName: '黎巴嫩',
    englishName: 'Lebanon',
    nativeName: 'لبنان',
  },
  {
    code: IsoCode.LC,
    dialingCode: '1758',
    id: '128',
    localizedName: '聖露西亞',
    englishName: 'Saint Lucia',
    nativeName: 'Saint Lucia',
  },
  {
    code: IsoCode.LI,
    dialingCode: '423',
    id: '129',
    localizedName: '列支敦斯登',
    englishName: 'Liechtenstein',
    nativeName: 'Liechtenstein',
  },
  {
    code: IsoCode.LK,
    dialingCode: '94',
    id: '130',
    localizedName: '斯里蘭卡',
    englishName: 'Sri Lanka',
    nativeName: 'śrī laṃkāva',
  },
  {
    code: IsoCode.LR,
    dialingCode: '231',
    id: '131',
    localizedName: '賴比瑞亞',
    englishName: 'Liberia',
    nativeName: 'Liberia',
  },
  {
    code: IsoCode.LS,
    dialingCode: '266',
    id: '132',
    localizedName: '賴索托',
    englishName: 'Lesotho',
    nativeName: 'Lesotho',
  },
  {
    code: IsoCode.LT,
    dialingCode: '370',
    id: '133',
    localizedName: '立陶宛',
    englishName: 'Lithuania',
    nativeName: 'Lietuva',
  },
  {
    code: IsoCode.LU,
    dialingCode: '352',
    id: '134',
    localizedName: '盧森堡',
    englishName: 'Luxembourg',
    nativeName: 'Luxembourg',
  },
  {
    code: IsoCode.LV,
    dialingCode: '371',
    id: '135',
    localizedName: '拉脫維亞',
    englishName: 'Latvia',
    nativeName: 'Latvija',
  },
  {
    code: IsoCode.LY,
    dialingCode: '218',
    id: '136',
    localizedName: '利比亞',
    englishName: 'Libya',
    nativeName: '‏ليبيا',
  },
  {
    code: IsoCode.MA,
    dialingCode: '212',
    id: '137',
    localizedName: '摩洛哥',
    englishName: 'Morocco',
    nativeName: 'المغرب',
  },
  {
    code: IsoCode.MC,
    dialingCode: '377',
    id: '138',
    localizedName: '摩納哥',
    englishName: 'Monaco',
    nativeName: 'Monaco',
  },
  {
    code: IsoCode.MD,
    dialingCode: '373',
    id: '139',
    localizedName: '摩爾多瓦',
    englishName: 'Moldova',
    nativeName: 'Moldova',
  },
  {
    code: IsoCode.ME,
    dialingCode: '382',
    id: '140',
    localizedName: '蒙特內哥羅',
    englishName: 'Montenegro',
    nativeName: 'Црна Гора',
  },
  {
    code: IsoCode.MF,
    dialingCode: '590',
    id: '141',
    localizedName: '法屬聖馬丁',
    englishName: 'Saint Martin',
    nativeName: 'Saint-Martin',
  },
  {
    code: IsoCode.MG,
    dialingCode: '261',
    id: '142',
    localizedName: '馬達加斯加',
    englishName: 'Madagascar',
    nativeName: 'Madagasikara',
  },
  {
    code: IsoCode.MH,
    dialingCode: '692',
    id: '143',
    localizedName: '馬紹爾群島',
    englishName: 'Marshall Islands',
    nativeName: 'M̧ajeļ',
  },
  {
    code: IsoCode.MK,
    dialingCode: '389',
    id: '144',
    localizedName: '北馬其頓',
    englishName: 'North Macedonia',
    nativeName: 'Северна Македонија',
  },
  {
    code: IsoCode.ML,
    dialingCode: '223',
    id: '145',
    localizedName: '馬利',
    englishName: 'Mali',
    nativeName: 'Mali',
  },
  {
    code: IsoCode.MM,
    dialingCode: '95',
    id: '146',
    localizedName: '緬甸',
    englishName: 'Myanmar [Burma]',
    nativeName: 'မြန်မာ',
  },
  {
    code: IsoCode.MN,
    dialingCode: '976',
    id: '147',
    localizedName: '蒙古',
    englishName: 'Mongolia',
    nativeName: 'Монгол улс',
  },
  {
    code: IsoCode.MO,
    dialingCode: '853',
    id: '148',
    localizedName: '澳門',
    englishName: 'Macao',
    nativeName: '澳門',
  },
  {
    code: IsoCode.MP,
    dialingCode: '1670',
    id: '149',
    localizedName: '北馬利安納群島',
    englishName: 'Northern Mariana Islands',
    nativeName: 'Northern Mariana Islands',
  },
  {
    code: IsoCode.MQ,
    dialingCode: '596',
    id: '150',
    localizedName: '馬丁尼克',
    englishName: 'Martinique',
    nativeName: 'Martinique',
  },
  {
    code: IsoCode.MR,
    dialingCode: '222',
    id: '151',
    localizedName: '茅利塔尼亞',
    englishName: 'Mauritania',
    nativeName: 'موريتانيا',
  },
  {
    code: IsoCode.MS,
    dialingCode: '1664',
    id: '152',
    localizedName: '蒙特塞拉特',
    englishName: 'Montserrat',
    nativeName: 'Montserrat',
  },
  {
    code: IsoCode.MT,
    dialingCode: '356',
    id: '153',
    localizedName: '馬爾他',
    englishName: 'Malta',
    nativeName: 'Malta',
  },
  {
    code: IsoCode.MU,
    dialingCode: '230',
    id: '154',
    localizedName: '模里西斯',
    englishName: 'Mauritius',
    nativeName: 'Maurice',
  },
  {
    code: IsoCode.MV,
    dialingCode: '960',
    id: '155',
    localizedName: '馬爾地夫',
    englishName: 'Maldives',
    nativeName: 'Maldives',
  },
  {
    code: IsoCode.MW,
    dialingCode: '265',
    id: '156',
    localizedName: '馬拉威',
    englishName: 'Malawi',
    nativeName: 'Malawi',
  },
  {
    code: IsoCode.MX,
    dialingCode: '52',
    id: '157',
    localizedName: '墨西哥',
    englishName: 'Mexico',
    nativeName: 'México',
  },
  {
    code: IsoCode.MY,
    dialingCode: '60',
    id: '158',
    localizedName: '馬來西亞',
    englishName: 'Malaysia',
    nativeName: 'Malaysia',
  },
  {
    code: IsoCode.MZ,
    dialingCode: '258',
    id: '159',
    localizedName: '莫三比克',
    englishName: 'Mozambique',
    nativeName: 'Moçambique',
  },
  {
    code: IsoCode.NA,
    dialingCode: '264',
    id: '160',
    localizedName: '納米比亞',
    englishName: 'Namibia',
    nativeName: 'Namibia',
  },
  {
    code: IsoCode.NC,
    dialingCode: '687',
    id: '161',
    localizedName: '新喀里多尼亞',
    englishName: 'New Caledonia',
    nativeName: 'Nouvelle-Calédonie',
  },
  {
    code: IsoCode.NE,
    dialingCode: '227',
    id: '162',
    localizedName: '尼日',
    englishName: 'Niger',
    nativeName: 'Niger',
  },
  {
    code: IsoCode.NF,
    dialingCode: '672',
    id: '163',
    localizedName: '諾福克島',
    englishName: 'Norfolk Island',
    nativeName: 'Norfolk Island',
  },
  {
    code: IsoCode.NG,
    dialingCode: '234',
    id: '164',
    localizedName: '奈及利亞',
    englishName: 'Nigeria',
    nativeName: 'Nigeria',
  },
  {
    code: IsoCode.NI,
    dialingCode: '505',
    id: '165',
    localizedName: '尼加拉瓜',
    englishName: 'Nicaragua',
    nativeName: 'Nicaragua',
  },
  {
    code: IsoCode.NL,
    dialingCode: '31',
    id: '166',
    localizedName: '荷蘭',
    englishName: 'Netherlands',
    nativeName: 'Nederland',
  },
  {
    code: IsoCode.NO,
    dialingCode: '47',
    id: '167',
    localizedName: '挪威',
    englishName: 'Norway',
    nativeName: 'Norge',
  },
  {
    code: IsoCode.NP,
    dialingCode: '977',
    id: '168',
    localizedName: '尼泊爾',
    englishName: 'Nepal',
    nativeName: 'नपल',
  },
  {
    code: IsoCode.NR,
    dialingCode: '674',
    id: '169',
    localizedName: '諾魯',
    englishName: 'Nauru',
    nativeName: 'Nauru',
  },
  {
    code: IsoCode.NU,
    dialingCode: '683',
    id: '170',
    localizedName: '紐埃',
    englishName: 'Niue',
    nativeName: 'Niuē',
  },
  {
    code: IsoCode.NZ,
    dialingCode: '64',
    id: '171',
    localizedName: '紐西蘭',
    englishName: 'New Zealand',
    nativeName: 'New Zealand',
  },
  {
    code: IsoCode.OM,
    dialingCode: '968',
    id: '172',
    localizedName: '阿曼',
    englishName: 'Oman',
    nativeName: 'عمان',
  },
  {
    code: IsoCode.PA,
    dialingCode: '507',
    id: '173',
    localizedName: '巴拿馬',
    englishName: 'Panama',
    nativeName: 'Panamá',
  },
  {
    code: IsoCode.PE,
    dialingCode: '51',
    id: '174',
    localizedName: '秘魯',
    englishName: 'Peru',
    nativeName: 'Perú',
  },
  {
    code: IsoCode.PF,
    dialingCode: '689',
    id: '175',
    localizedName: '法屬玻里尼西亞',
    englishName: 'French Polynesia',
    nativeName: 'Polynésie française',
  },
  {
    code: IsoCode.PG,
    dialingCode: '675',
    id: '176',
    localizedName: '巴布亞紐幾內亞',
    englishName: 'Papua New Guinea',
    nativeName: 'Papua Niugini',
  },
  {
    code: IsoCode.PH,
    dialingCode: '63',
    id: '177',
    localizedName: '菲律賓',
    englishName: 'Philippines',
    nativeName: 'Pilipinas',
  },
  {
    code: IsoCode.PK,
    dialingCode: '92',
    id: '178',
    localizedName: '巴基斯坦',
    englishName: 'Pakistan',
    nativeName: 'Pakistan',
  },
  {
    code: IsoCode.PL,
    dialingCode: '48',
    id: '179',
    localizedName: '波蘭',
    englishName: 'Poland',
    nativeName: 'Polska',
  },
  {
    code: IsoCode.PM,
    dialingCode: '508',
    id: '180',
    localizedName: '聖皮埃與密克隆群島',
    englishName: 'Saint Pierre and Miquelon',
    nativeName: 'Saint-Pierre-et-Miquelon',
  },
  {
    code: IsoCode.PN,
    dialingCode: '64',
    id: '181',
    localizedName: '皮特凱恩群島',
    englishName: 'Pitcairn Islands',
    nativeName: 'Pitcairn Islands',
  },
  {
    code: IsoCode.PR,
    dialingCode: '1787,1939',
    id: '182',
    localizedName: '波多黎各',
    englishName: 'Puerto Rico',
    nativeName: 'Puerto Rico',
  },
  {
    code: IsoCode.PS,
    dialingCode: '970',
    id: '183',
    localizedName: '巴勒斯坦',
    englishName: 'Palestine',
    nativeName: 'فلسطين',
  },
  {
    code: IsoCode.PT,
    dialingCode: '351',
    id: '184',
    localizedName: '葡萄牙',
    englishName: 'Portugal',
    nativeName: 'Portugal',
  },
  {
    code: IsoCode.PW,
    dialingCode: '680',
    id: '185',
    localizedName: '帛琉',
    englishName: 'Palau',
    nativeName: 'Palau',
  },
  {
    code: IsoCode.PY,
    dialingCode: '595',
    id: '186',
    localizedName: '巴拉圭',
    englishName: 'Paraguay',
    nativeName: 'Paraguay',
  },
  {
    code: IsoCode.QA,
    dialingCode: '974',
    id: '187',
    localizedName: '卡達',
    englishName: 'Qatar',
    nativeName: 'قطر',
  },
  {
    code: IsoCode.RE,
    dialingCode: '262',
    id: '188',
    localizedName: '留尼旺',
    englishName: 'Réunion',
    nativeName: 'La Réunion',
  },
  {
    code: IsoCode.RO,
    dialingCode: '40',
    id: '189',
    localizedName: '羅馬尼亞',
    englishName: 'Romania',
    nativeName: 'România',
  },
  {
    code: IsoCode.RS,
    dialingCode: '381',
    id: '190',
    localizedName: '塞爾維亞',
    englishName: 'Serbia',
    nativeName: 'Србија',
  },
  {
    code: IsoCode.RU,
    dialingCode: '7',
    id: '191',
    localizedName: '俄羅斯',
    englishName: 'Russia',
    nativeName: 'Россия',
  },
  {
    code: IsoCode.RW,
    dialingCode: '250',
    id: '192',
    localizedName: '盧安達',
    englishName: 'Rwanda',
    nativeName: 'Rwanda',
  },
  {
    code: IsoCode.SA,
    dialingCode: '966',
    id: '193',
    localizedName: '沙烏地阿拉伯',
    englishName: 'Saudi Arabia',
    nativeName: 'العربية السعودية',
  },
  {
    code: IsoCode.SB,
    dialingCode: '677',
    id: '194',
    localizedName: '索羅門群島',
    englishName: 'Solomon Islands',
    nativeName: 'Solomon Islands',
  },
  {
    code: IsoCode.SC,
    dialingCode: '248',
    id: '195',
    localizedName: '塞席爾',
    englishName: 'Seychelles',
    nativeName: 'Seychelles',
  },
  {
    code: IsoCode.SD,
    dialingCode: '249',
    id: '196',
    localizedName: '蘇丹',
    englishName: 'Sudan',
    nativeName: 'السودان',
  },
  {
    code: IsoCode.SE,
    dialingCode: '46',
    id: '197',
    localizedName: '瑞典',
    englishName: 'Sweden',
    nativeName: 'Sverige',
  },
  {
    code: IsoCode.SG,
    dialingCode: '65',
    id: '198',
    localizedName: '新加坡',
    englishName: 'Singapore',
    nativeName: 'Singapore',
  },
  {
    code: IsoCode.SH,
    dialingCode: '290',
    id: '199',
    localizedName: '聖赫倫那、阿森松和特里斯坦-達庫尼亞',
    englishName: 'Saint Helena',
    nativeName: 'Saint Helena',
  },
  {
    code: IsoCode.SI,
    dialingCode: '386',
    id: '200',
    localizedName: '斯洛維尼亞',
    englishName: 'Slovenia',
    nativeName: 'Slovenija',
  },
  {
    code: IsoCode.SJ,
    dialingCode: '4779',
    id: '201',
    localizedName: '斯瓦爾巴和揚馬延',
    englishName: 'Svalbard and Jan Mayen',
    nativeName: 'Svalbard og Jan Mayen',
  },
  {
    code: IsoCode.SK,
    dialingCode: '421',
    id: '202',
    localizedName: '斯洛伐克',
    englishName: 'Slovakia',
    nativeName: 'Slovensko',
  },
  {
    code: IsoCode.SL,
    dialingCode: '232',
    id: '203',
    localizedName: '獅子山',
    englishName: 'Sierra Leone',
    nativeName: 'Sierra Leone',
  },
  {
    code: IsoCode.SM,
    dialingCode: '378',
    id: '204',
    localizedName: '聖馬利諾',
    englishName: 'San Marino',
    nativeName: 'San Marino',
  },
  {
    code: IsoCode.SN,
    dialingCode: '221',
    id: '205',
    localizedName: '塞內加爾',
    englishName: 'Senegal',
    nativeName: 'Sénégal',
  },
  {
    code: IsoCode.SO,
    dialingCode: '252',
    id: '206',
    localizedName: '索馬利亞',
    englishName: 'Somalia',
    nativeName: 'Soomaaliya',
  },
  {
    code: IsoCode.SR,
    dialingCode: '597',
    id: '207',
    localizedName: '蘇利南',
    englishName: 'Suriname',
    nativeName: 'Suriname',
  },
  {
    code: IsoCode.SS,
    dialingCode: '211',
    id: '208',
    localizedName: '南蘇丹',
    englishName: 'South Sudan',
    nativeName: 'South Sudan',
  },
  {
    code: IsoCode.ST,
    dialingCode: '239',
    id: '209',
    localizedName: '聖多美普林西比',
    englishName: 'São Tomé and Príncipe',
    nativeName: 'São Tomé e Príncipe',
  },
  {
    code: IsoCode.SV,
    dialingCode: '503',
    id: '210',
    localizedName: '薩爾瓦多',
    englishName: 'El Salvador',
    nativeName: 'El Salvador',
  },
  {
    code: IsoCode.SX,
    dialingCode: '1721',
    id: '211',
    localizedName: '荷屬聖馬丁',
    englishName: 'Sint Maarten',
    nativeName: 'Sint Maarten',
  },
  {
    code: IsoCode.SY,
    dialingCode: '963',
    id: '212',
    localizedName: '敘利亞',
    englishName: 'Syria',
    nativeName: 'سوريا',
  },
  {
    code: IsoCode.SZ,
    dialingCode: '268',
    id: '213',
    localizedName: '史瓦帝尼',
    englishName: 'Swaziland',
    nativeName: 'Swaziland',
  },
  {
    code: IsoCode.TC,
    dialingCode: '1649',
    id: '214',
    localizedName: '特克斯與凱科斯群島',
    englishName: 'Turks and Caicos Islands',
    nativeName: 'Turks and Caicos Islands',
  },
  {
    code: IsoCode.TD,
    dialingCode: '235',
    id: '215',
    localizedName: '查德',
    englishName: 'Chad',
    nativeName: 'Tchad',
  },
  {
    code: IsoCode.TF,
    dialingCode: '262',
    id: '216',
    localizedName: '法屬南部和南極領地',
    englishName: 'French Southern Territories',
    nativeName: 'Territoire des Terres australes et antarctiques fr',
  },
  {
    code: IsoCode.TG,
    dialingCode: '228',
    id: '217',
    localizedName: '多哥',
    englishName: 'Togo',
    nativeName: 'Togo',
  },
  {
    code: IsoCode.TH,
    dialingCode: '66',
    id: '218',
    localizedName: '泰國',
    englishName: 'Thailand',
    nativeName: 'ประเทศไทย',
  },
  {
    code: IsoCode.TJ,
    dialingCode: '992',
    id: '219',
    localizedName: '塔吉克',
    englishName: 'Tajikistan',
    nativeName: 'Тоҷикистон',
  },
  {
    code: IsoCode.TK,
    dialingCode: '690',
    id: '220',
    localizedName: '托克勞',
    englishName: 'Tokelau',
    nativeName: 'Tokelau',
  },
  {
    code: IsoCode.TL,
    dialingCode: '670',
    id: '221',
    localizedName: '東帝汶',
    englishName: 'East Timor',
    nativeName: 'Timor-Leste',
  },
  {
    code: IsoCode.TM,
    dialingCode: '993',
    id: '222',
    localizedName: '土庫曼',
    englishName: 'Turkmenistan',
    nativeName: 'Türkmenistan',
  },
  {
    code: IsoCode.TN,
    dialingCode: '216',
    id: '223',
    localizedName: '突尼西亞',
    englishName: 'Tunisia',
    nativeName: 'تونس',
  },
  {
    code: IsoCode.TO,
    dialingCode: '676',
    id: '224',
    localizedName: '東加',
    englishName: 'Tonga',
    nativeName: 'Tonga',
  },
  {
    code: IsoCode.TR,
    dialingCode: '90',
    id: '225',
    localizedName: '土耳其',
    englishName: 'Turkey',
    nativeName: 'Türkiye',
  },
  {
    code: IsoCode.TT,
    dialingCode: '1868',
    id: '226',
    localizedName: '千里達及托巴哥',
    englishName: 'Trinidad and Tobago',
    nativeName: 'Trinidad and Tobago',
  },
  {
    code: IsoCode.TV,
    dialingCode: '688',
    id: '227',
    localizedName: '吐瓦魯',
    englishName: 'Tuvalu',
    nativeName: 'Tuvalu',
  },
  {
    code: IsoCode.TW,
    dialingCode: '886',
    id: '228',
    localizedName: '臺灣',
    englishName: 'Taiwan',
    nativeName: '臺灣',
  },
  {
    code: IsoCode.TZ,
    dialingCode: '255',
    id: '229',
    localizedName: '坦尚尼亞',
    englishName: 'Tanzania',
    nativeName: 'Tanzania',
  },
  {
    code: IsoCode.UA,
    dialingCode: '380',
    id: '230',
    localizedName: '烏克蘭',
    englishName: 'Ukraine',
    nativeName: 'Україна',
  },
  {
    code: IsoCode.UG,
    dialingCode: '256',
    id: '231',
    localizedName: '烏干達',
    englishName: 'Uganda',
    nativeName: 'Uganda',
  },
  {
    code: IsoCode.UM,
    dialingCode: '1',
    id: '232',
    localizedName: '美國本土外小島嶼',
    englishName: 'U.S. Minor Outlying Islands',
    nativeName: 'United States Minor Outlying Islands',
  },
  {
    code: IsoCode.US,
    dialingCode: '1',
    id: '233',
    localizedName: '美國',
    englishName: 'United States',
    nativeName: 'United States',
  },
  {
    code: IsoCode.UY,
    dialingCode: '598',
    id: '234',
    localizedName: '烏拉圭',
    englishName: 'Uruguay',
    nativeName: 'Uruguay',
  },
  {
    code: IsoCode.UZ,
    dialingCode: '998',
    id: '235',
    localizedName: '烏茲別克',
    englishName: 'Uzbekistan',
    nativeName: 'O‘zbekiston',
  },
  {
    code: IsoCode.VA,
    dialingCode: '379',
    id: '236',
    localizedName: '梵蒂岡',
    englishName: 'Vatican City',
    nativeName: 'Vaticano',
  },
  {
    code: IsoCode.VC,
    dialingCode: '1784',
    id: '237',
    localizedName: '聖文森及格瑞那丁',
    englishName: 'Saint Vincent and the Grenadines',
    nativeName: 'Saint Vincent and the Grenadines',
  },
  {
    code: IsoCode.VE,
    dialingCode: '58',
    id: '238',
    localizedName: '委內瑞拉',
    englishName: 'Venezuela',
    nativeName: 'Venezuela',
  },
  {
    code: IsoCode.VG,
    dialingCode: '1284',
    id: '239',
    localizedName: '英屬維京群島',
    englishName: 'British Virgin Islands',
    nativeName: 'British Virgin Islands',
  },
  {
    code: IsoCode.VI,
    dialingCode: '1340',
    id: '240',
    localizedName: '美屬維京群島',
    englishName: 'U.S. Virgin Islands',
    nativeName: 'United States Virgin Islands',
  },
  {
    code: IsoCode.VN,
    dialingCode: '84',
    id: '241',
    localizedName: '越南',
    englishName: 'Vietnam',
    nativeName: 'Việt Nam',
  },
  {
    code: IsoCode.VU,
    dialingCode: '678',
    id: '242',
    localizedName: '萬那杜',
    englishName: 'Vanuatu',
    nativeName: 'Vanuatu',
  },
  {
    code: IsoCode.WF,
    dialingCode: '681',
    id: '243',
    localizedName: '瓦利斯和富圖那',
    englishName: 'Wallis and Futuna',
    nativeName: 'Wallis et Futuna',
  },
  {
    code: IsoCode.WS,
    dialingCode: '685',
    id: '244',
    localizedName: '薩摩亞',
    englishName: 'Samoa',
    nativeName: 'Samoa',
  },
  {
    code: IsoCode.XK,
    dialingCode: '383',
    id: '245',
    localizedName: '科索沃',
    englishName: 'Kosovo',
    nativeName: 'Republika e Kosovës',
  },
  {
    code: IsoCode.YE,
    dialingCode: '967',
    id: '246',
    localizedName: '葉門',
    englishName: 'Yemen',
    nativeName: 'اليَمَن',
  },
  {
    code: IsoCode.YT,
    dialingCode: '262',
    id: '247',
    localizedName: '馬約特',
    englishName: 'Mayotte',
    nativeName: 'Mayotte',
  },
  {
    code: IsoCode.ZA,
    dialingCode: '27',
    id: '248',
    localizedName: '南非',
    englishName: 'South Africa',
    nativeName: 'South Africa',
  },
  {
    code: IsoCode.ZM,
    dialingCode: '260',
    id: '249',
    localizedName: '尚比亞',
    englishName: 'Zambia',
    nativeName: 'Zambia',
  },
  {
    code: IsoCode.ZW,
    dialingCode: '263',
    id: '250',
    localizedName: '辛巴威',
    englishName: 'Zimbabwe',
    nativeName: 'Zimbabwe',
  },
];
