export enum AnimationType {
  FadeInTop = 'fade-in-top',
  FadeInRight = 'fade-in-right',
  FadeInBottom = 'fade-in-bottom',
  FadeInLeft = 'fade-in-left',
  ZoomIn = 'zoom-in',
  ZoomOut = 'zoom-out',
  FadeOutTop = 'fade-out-top',
  FadeOutRight = 'fade-out-right',
  FadeOutBottom = 'fade-out-bottom',
  FadeOutLeft = 'fade-out-left',
  Twink = 'twink',
  Magnification = 'magnification',
  Rotate = 'rotate',
  Dash = 'dash',
  Ripple = 'ripple',
  Flashing = 'flashing',
}
