export enum GaEvent {
  /** 登入-登入帳號數量 */
  Login = 'login',
  /** 註冊-註冊帳號數量 */
  SignUp = 'sign_up',
  /** 搜尋-搜尋_簡易盤 */
  Search = 'search',
  /** 分享-分享賺錢功能_複製連結/面對面掃碼/通訊軟體/ */
  Share = 'share',
  /** 加入聊天室-進入盤口聊天室 */
  JoinGroup = 'join_group',
  /** 選擇注單-點選注單至購物車 */
  SelectContent = 'select_content',
  RegistrationStart = 'reg_start',
  /** 開始註冊 */
  GrmStartRegistration = 'grm_start_registration',
  /** 完成註冊 */
  GrmComplete_registration = 'grm_complete_registration',
  /** 登錄 */
  GrmLogin = 'grm_login',
  /** 開始充值 */
  GrmRechargeStart = 'grm_recharge_start',
  /** 提交充值 */
  GrmRechargeRequestSuccess = 'grm_recharge_request_success',
  /** 首充成功 */
  GrmRechargeFirstSuccess = 'grm_recharge_first_success',
  /** 二充成功 */
  GrmRechargeSubsequentSuccess = 'grm_recharge_subsequent_success',
}
