export enum WalletBank {
  Fudou_Cny = 'FUDOU_CNY',
  V808_Cny = 'V808_CNY',
  Cfb_Cny = 'CFB_CNY',
  Xxpay_Cny = 'XXPAY_CNY',
  Koipay_Cny = 'KOIPAY_CNY',
  Yibifu_Cny = 'YIBIFU_CNY',
  Bobi_Cny = 'BOBI_CNY',
  Wanbi_Cny = 'WANBI_CNY',
  Topay_Cny = 'TOPAY_CNY',
  Qianneng_Cny = 'QIANNENG_CNY',
  Abpay_Cny = 'ABPAY_CNY',
  Gopay_Cny = 'GOPAY_CNY',
  Cloudpay_Cny = 'CLOUDPAY_CNY',
  Okpay_Cny = 'OKPAY_CNY',
  Cgpay_Cny = 'CGPPAY_CNY',
  Gppay_Cny = 'GPPAY_CNY',
  V88pay_Cny = 'V88PAY_CNY',
  Ebpay_Cny = 'EBPAY_CNY',
  V988pay_Cny = 'V988PAY_CNY',
  Samlepay_Cny = 'SAMLEPAY_CNY',
  Cbrpay_CNY = 'CBRPAY_CNY',
  Kdpay_CNY = 'KDPAY_CNY',
}
